version: '3'
services:
  mysql:
    image: mysql:8.0.18
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - volumes:
          # про data завтра распишу в видео/статье
          # - //c/Docker/pg-data:/var/lib/postgresql/data
          # про ДЗ - вам нужно схему положить сюда (вместо init.sql)
          - //c/Docker/pg-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass